services:
  api:
    build:
      context: ./MasterDataImporter
      dockerfile: Dockerfile
    container_name: masterdata-api
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Host=pendio-postgres;Port=5432;Database=masterdata;Username=pendio;Password=pendio
    networks:
      - pendio-network
    restart: unless-stopped

networks:
  pendio-network:
    external: true
    name: pendio_pendio-network
